PARAMETERS:
  p_rad1 RADIOBUTTON GROUP rad USER-COMMAND cmd DEFAULT 'X',
  p_rad2 RADIOBUTTON GROUP rad,
  p_rad3 RADIOBUTTON GROUP rad.

SELECTION-SCREEN BEGIN OF BLOCK b1 WITH FRAME.
  SELECT-OPTIONS s_schema FOR lv_schema MODIF ID mod.
  PARAMETERS p_disk TYPE int4 MODIF ID mod.
SELECTION-SCREEN END OF BLOCK b1.
